import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    networkStatusBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      zIndex: 1000,
    },
    statusToggleButton: {
      position: 'absolute',
      top: Spacing.sm,
      right: Spacing.sm,
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 999,
      borderWidth: 1,
      borderColor: theme.border,
    },
    statusIndicator: {
      position: 'absolute',
      top: Spacing.sm,
      right: Spacing.sm,
      width: 240,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
      zIndex: 998,
    },
    statusIndicatorHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    statusIndicatorTitle: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      marginLeft: Spacing.sm,
    },
    statusIndicatorContent: {
      padding: Spacing.md,
    },
    statusRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    statusLabel: {
      fontSize: 12,
    },
    statusValue: {
      fontSize: 12,
      fontWeight: '600',
    },
    statusHint: {
      marginTop: Spacing.sm,
      padding: Spacing.sm,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusHintText: {
      flex: 1,
      fontSize: 11,
      marginLeft: Spacing.sm,
    },
    webView: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    loadingContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundRoot,
    },
    backHint: {
      position: 'absolute',
      bottom: Spacing.xl,
      left: 0,
      right: 0,
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      marginHorizontal: Spacing.xl,
      borderRadius: BorderRadius.full,
    },
  });
};
